spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/spring
    username: root
    password: root

  mvc:
    static-path-pattern: /static/**

  thymeleaf:
    prefix: classpath:static/   #타임리프 루트경로
    suffix: .html     #확장자 생략
    check-template-location: true   #??

server:
  port: 8083

